# SPDX-FileCopyrightText: Copyright (c) 2019-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
inherit_from: config/default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  SuggestExtensions: false
  NewCops: enable
  EnabledByDefault: true
require:
  - ./lib/rubocop-elegant
plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
Naming/FileName:
  Exclude:
    - 'lib/rubocop-elegant.rb'
    - 'test/test_rubocop-elegant.rb'
