# SPDX-FileCopyrightText: Copyright (c) 2019-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
Elegant:
  Enabled: true
  DocumentationBaseURL: https://github.com/yegor256/rubocop-elegant
Elegant/NoComments:
  Description: 'Disallows comments in source code, except SPDX license comments'
  Enabled: true
  VersionAdded: '0.0.1'
Elegant/NoEmptyLinesInMethods:
  Description: 'Disallows empty lines inside method bodies'
  Enabled: true
  VersionAdded: '0.0.2'
Elegant/GoodVariableName:
  Description: 'Checks that variable names match the configured pattern'
  Enabled: true
  VersionAdded: '0.0.3'
  Pattern: '^(@{1,2}|\$)?(the_|test_|fake_)?[a-z]{1,16}$'
Elegant/GoodMethodName:
  Description: 'Checks that method names match the configured pattern'
  Enabled: true
  VersionAdded: '0.0.3'
  Pattern: '^((fake_|the_)?[a-z]{1,16}[!?]?|test_[a-z_]+|on_[a-z_]+)$'

Naming/VariableName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 100
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Max: 50
Style/IfUnlessModifier:
  Enabled: false
Naming/FileName:
  Regex: '^[a-z0-9\-._]*$'
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/ParameterAlignment:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/MultilineBlockChain:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/RequireOrder:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/Send:
  Enabled: true
Style/StaticClass:
  Enabled: true
Style/TopLevelMethodDefinition:
  Enabled: true
  Exclude:
    - 'Rakefile'
Style/ImplicitRuntimeError:
  Enabled: true
Style/DateTime:
  Enabled: true
Lint/NumberConversion:
  Enabled: true
Performance/ChainArrayAllocation:
  Enabled: true
Performance/OpenStruct:
  Enabled: true
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
